SoftwareMonitoringSystem/SoftwareMonitoringSystem/Controllers/DevMGMTController.cs
using SoftwareMonitoringSystem.Infrastructure.Abstract;
using SoftwareMonitoringSystem.Infrastructure.Concrete;
using SoftwareMonitoringSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Collections.Specialized;
using System.Net.Sockets;
using System.Net;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using System.Text;
using System.Net.Http;
using System.Threading;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.IO;

namespace SoftwareMonitoringSystem.Controllers
{
    // Require authorization for all actions on the controller.
    [Authorize]
    public class DevMGMTController : Controller
    {
        IAuthProvider authProvider;
        public DevMGMTController()
        {
            authProvider = new FormsAuthProvider();
        }
        // GET: DevMGMT.
        public ActionResult GetDevices()
        {
            authProvider.CheckDefaultPassword(this);
            List<Device> devices = null;
            using (var dbContext = new SMSDBContext())
            {
                devices = dbContext.Devices.ToList();
                devices.Reverse();
            }
            //lista urzadzen
            return View("DevManagement", devices);
        }

        // GET: DevMGMT/Details/5.
        public ActionResult Details(int id)
        {
            authProvider.CheckDefaultPassword(this);
            return View();
        }


        // POST: DevMGMT/Create.
        [HttpPost]
        public JsonResult AddDevice(string MACAddress, string _Model, string IPAddress, string Description)
        {
            try
            {
                if (_Model == "")
                {
                    return Json("Uzupełnij pole Model");
                }
                using (var dbContext = new SMSDBContext())
                {
                    Regex MACAddr = new Regex(@"^[a-fA-F0-9-]{17}|[a-fA-F0-9:]{17}$");
                    if (MACAddr.IsMatch(MACAddress))
                    {
                        if (dbContext.Devices.Count(x => x.MACAddress.Equals(MACAddress)) > 0)
                        {
                            return Json("Wpisz inny adres MAC (podany jest zajęty)");
                        }
                    }
                    else
                    {
                        return Json("Wpisz poprawny adres MAC");
                    }
                    Regex IPv4Addr = new Regex(@"^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(:[0-9]{1,5})?$");
                    if (IPv4Addr.IsMatch(IPAddress))
                    {
                        if (dbContext.Devices.Count(x => x.IPAddress.Equals(IPAddress)) > 0)
                        {
                            return Json("Wpisz inny adres IP (podany jest zajęty)");
                        }
                    }
                    else
                    {
                        return Json("Wpisz poprawny adres IP");
                    }

                    Device device = new Device();
                    device.MACAddress = MACAddress;
                    device.Model = _Model;
                    device.IPAddress = IPAddress;
                    device.Description = Description;
                    dbContext.Devices.Add(device);
                    dbContext.SaveChanges();
                    return Json(device);
                }
            }
            catch
            {
                return Json("Spróbuj ponownie (błąd wewnętrzny aplikacji)");
            }
        }

        [HttpPost]
        public ActionResult Edit(int DeviceID, string MACAddress, string Model, string IPAddress, string Description)
        {
            if (DeviceID > 0 && MACAddress != "" && Model != "" && IPAddress != "")
            {
                Regex MACAddr = new Regex(@"^[a-fA-F0-9-]{17}|[a-fA-F0-9:]{17}$");
                Regex IPv4Addr = new Regex(@"^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(:[0-9]{1,5})?$");
                if (MACAddr.IsMatch(MACAddress))
                {
                    using (var dbContext = new SMSDBContext())
                    {
                        if (dbContext.Devices.Count(x => x.MACAddress.Equals(MACAddress) && x.DeviceID!=DeviceID) > 0)
                        {
                            return Json("Wpisz inny adres MAC (podany jest zajęty)");
                        }
                        else
                        {
                            if (IPv4Addr.IsMatch(IPAddress))
                            {
                                if (dbContext.Devices.Count(x => x.IPAddress.Equals(IPAddress) && x.DeviceID!=DeviceID) > 0)
                                {
                                    return Json("Wpisz inny adres IP (podany jest zajęty)");
                                }
                                else
                                {
                                    Device dev = dbContext.Devices.SingleOrDefault(x => x.DeviceID.Equals(DeviceID));
                                    dev.MACAddress = MACAddress;
                                    dev.Model = Model;
                                    dev.IPAddress = IPAddress;
                                    dev.Description = Description;
                                    dev.IsActive = 1;
                                    dbContext.Entry(dev).State = EntityState.Modified;
                                    dbContext.SaveChanges();
                                    return Json("Success");
                                }
                            }
                            else
                            {
                                return Json("Wpisz prawidłowy adres IP");
                            }
                        }
                    }
                }
                else
                {
                    return Json("Wpisz prawidłowy adres MAC");
                }

            }
            else
            {
                return Json("Spróbuj ponownie (błąd wewnętrzny aplikacji)");
            }
        }

        // POST: DevMGMT/Delete/5.
        [HttpPost]
        public ActionResult Delete(List<int> IDs)
        {
            try
            {
                using (var dbContext = new SMSDBContext())
                {
                    Device device;
                    foreach (int item in IDs)
                    {
                        var scansAndDevices = dbContext.ScansAndDevices.Where(x => x.DeviceID == item);
                        // Remove from ScansAndDevices.
                        foreach (var sd2 in scansAndDevices)
                        {
                            if (sd2 != null)
                            {
                                dbContext.ScansAndDevices.Remove(sd2);
                            }
                        }
                        // Remove from Scans.
                        var sc_and_dev = dbContext.ScansAndDevices;
                        foreach (var sd1 in scansAndDevices)
                        {
                            if (sd1 != null)
                            {
                                var sc_c = dbContext.Scans.Where(x => x.ScanID == sd1.ScanID).FirstOrDefault();
                                if (sc_c!=null)
                                {
                                    if (sc_and_dev.Select(x=>x.ScanID == sd1.ScanID).Count()==0)
                                    {
                                        dbContext.Scans.Remove(sc_c);
                                    }
                                }
                            }
                        }

                        device = dbContext.Devices.SingleOrDefault(dev => dev.DeviceID == item);
                        if (device != null)
                        {
                            dbContext.Devices.Remove(device);
                            //******
                            try
                            {
                                string path = System.AppDomain.CurrentDomain.BaseDirectory + "bin\\Scans\\" + device.MACAddress;
                                if (Directory.Exists(path))
                                {
                                    Directory.Delete(path, true);
                                }
                            }
                            catch (Exception e)
                            {

                            }
                        }
                        else
                        {
                            return Json("Błąd wewnętrzny systemu");
                        }
                    }
                    dbContext.SaveChanges();
                    return Json("Success");
                }
            }
            catch
            {
                return Json("Błąd wewnętrzny systemu");
            }
        }
        [HttpGet]
        public ActionResult ScanHistory()
        {
            authProvider.CheckDefaultPassword(this);
            // Dictionary: KEY: DateTime, Value: D_S_IDDescStatus.
            Dictionary<DateTime, List<D_S_IDDescStatus>> dict = new Dictionary<DateTime, List<D_S_IDDescStatus>>();
            using (var context = new SMSDBContext())
            {
                List<Scan> scans = context.Scans.OrderByDescending(x=>x.ScanDateTime).ToList();
                if (scans.Count>0)
                {
                    List<ScanAndDevice> scansAndDevices = context.ScansAndDevices.ToList();
                    if (scansAndDevices.Count>0)
                    {
                        var devices = context.Devices.Select(x=>new {x.DeviceID, x.Description, x.IPAddress, x.MACAddress }).ToList();
                        if (devices.Count>0)
                        {

SoftwareMonitoringSystem/SoftwareMonitoringSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SSO</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/AdjustedSite.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color:white;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span> SSO
                </a>
            </div>
            @if (Request.IsAuthenticated)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#changePassModal" name="changePassBtn" role="button" class="btn" style="margin-top: 2px" data-toggle="modal" data-backdrop="static">Zmiana hasła</a></li>
                        <li>@Html.ActionLink("Historia skanowań", "ScanHistory", "DevMGMT", null, new { @style = "margin-top:3px;" })</li>
                    </ul>
                    @using (Html.BeginForm("LogOut", "Home", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <ul class="nav navbar-nav navbar-right">
                            <li style="background-color:transparent">
                                <a href="javascript:document.getElementById('logoutForm').submit()"><span class="glyphicon glyphicon-log-out"></span> Wyloguj</a>
                            </li>
                        </ul>
                    }
                </div>
            }
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div class="footer">
            <strong>Sieciowy skaner oprogramowania</strong>
            <br />
            @DateTime.Now.Year
        </div>
    </div>

    @if (Request.IsAuthenticated)
    {
        <div id="changePassModal" class="modal fade">
            <div class="modal-dialog" style="max-width:340px">
                <div class="modal-content">
                    @using (Html.BeginForm("ChangePass", "Home", FormMethod.Post, new { @id = "ChangePassForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="modal-header modal-header-blue">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Zmiana hasła</h4>
                        </div>
                        <div class="modal-body form-horizontal">
                            <div id="alertChangePass" class="alert alert-danger" style="display:none">
                                <strong>Uwaga!</strong> Zmień domyślne hasło
                            </div>
                            <div id="alertSuccessChangePass" class="alert alert-success" style="display:none">
                                <strong>Sukces!</strong> Hasło zostało zmienione pomyślnie
                            </div>
                            <div id="alertErrorChangePass" class="alert alert-danger" style="display:none">
                                Error
                            </div>
                            <div style="margin-bottom:5px;">
                                @Html.Editor("actualP", null, "actualP", new { htmlAttributes = new { @class = "form-control", @value = "", @placeholder = "Aktualne hasło", @required = "", @type = "password" } })
                            </div>
                            <div style="margin-bottom:5px;">
                                @Html.Editor("newP", null, "newP", new { htmlAttributes = new { @class = "form-control", @value = "", @placeholder = "Nowe hasło", @required = "", @type = "password" } })
                            </div>
                            <div style="margin-bottom:5px;">
                                @Html.Editor("confirmNewP", null, "confirmNewP", new { htmlAttributes = new { @class = "form-control", @value = "", @placeholder = "Potwierdź nowe hasło", @required = "", @type = "password" } })
                            </div>
                        </div>
                        <div class="modal-footer" style="margin-top:0px;">
                            <button type="button" class="btn btn-default" data-dismiss="modal" style="width:80px;">Anuluj</button>
                            <input type="submit" value="Zmień" class="btn btn-primary" style="width:80px" />
                        </div>
                    }
                </div>
            </div>
        </div>
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @if (Request.IsAuthenticated)
    {
        <script type="text/javascript">
            $(function () {
                var state = '@Session["ChangePassword"]';
               
                if (state=='True') {
                    $("#alertChangePass").show();
                    $("#changePassModal").modal();
                }

                $("#ChangePassForm").on('submit', function (e) {
                e.preventDefault() // prevent the form's normal submission
                var dataToPost = $(this).serialize()

                $.post('@Url.Action("ChangePass", "Home")', dataToPost)
                    .done(function (response, status, jqxhr) {
                        if (response == "Success") {
                            document.getElementById("actualP").value='';
                            document.getElementById("newP").value = '';
                            document.getElementById("confirmNewP").value = '';
                            $("#alertChangePass").hide();
                            $("#alertErrorChangePass").hide();
                            $("#alertSuccessChangePass").show();
                        }
                        else {
                            $("#alertErrorChangePass")[0].innerHTML = 'Uwaga! '.bold() + response;
                            $("#alertErrorChangePass").show();
                            $("#alertSuccessChangePass").hide();
                        }
                    })
                    .fail(function (jqxhr, status, error) {
                        $("#alertErrorChangePass")[0].innerHTML = 'Uwaga! '.bold() + "Spróbuj ponownie (błąd wewnętrzny aplikacji)";
                        $("#alertErrorChangePass").show();
                        $("#alertSuccessChangePass").hide();
                    })
                })

                $("#changePassModal").on("hidden.bs.modal", function () {
                    document.getElementById("actualP").value = '';
                    document.getElementById("newP").value = '';
                    document.getElementById("confirmNewP").value = '';
                    $("#alertErrorChangePass").hide();
                    $("#alertSuccessChangePass").hide();
                })

            })
        </script>
    }

</body>
</html>